/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Creative\Programming\Projects\portfolio\public\assets\Models\lo-fi_study_girlroom.glb 
Author: 雨花Rain flower (https://sketchfab.com/applekh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lo-fi-study-girlroom-cd5c5ec1107e42558f692b316462ccfb
Title: Lo-Fi Study Girl(room)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
// import { GroupProps } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';
import { MeshStandardMaterial, Mesh } from 'three'
import { useControls } from 'leva';


type GLTFResult = GLTF & {
  nodes: {
    [key: string]: Mesh;
    Object_4: Mesh;
    Object_7: Mesh;
    Object_10: Mesh;
    Object_13: Mesh;
    Object_16: Mesh;
    Object_19: Mesh;
    Object_22: Mesh;
    Object_25: Mesh;
    Object_28: Mesh;
    Object_31: Mesh;
    Object_34: Mesh;
    Object_37: Mesh;
    Object_40: Mesh;
    Object_43: Mesh;
    Object_46: Mesh;
    Object_49: Mesh;
    Object_52: Mesh;
    Object_55: Mesh;
    Object_58: Mesh;
    Object_61: Mesh;
    Object_64: Mesh;
    Object_67: Mesh;
    Object_70: Mesh;
    Object_73: Mesh;
    Object_76: Mesh;
    Object_79: Mesh;
    Object_82: Mesh;
    Object_85: Mesh;
    Object_88: Mesh;
    Object_91: Mesh;
    Object_94: Mesh;
    Object_97: Mesh;
    Object_100: Mesh;
    Object_103: Mesh;
    Object_106: Mesh;
    Object_109: Mesh;
    Object_112: Mesh;
    Object_115: Mesh;
    Object_118: Mesh;
    Object_121: Mesh;
    Object_124: Mesh;
    Object_127: Mesh;
    Object_130: Mesh;
    Object_133: Mesh;
    Object_136: Mesh;
    Object_139: Mesh;
    Object_142: Mesh;
    Object_145: Mesh;
    Object_148: Mesh;
    Object_152: Mesh;
    Object_155: Mesh;
    Object_158: Mesh;
    Object_162: Mesh;
    Object_165: Mesh;
    Object_168: Mesh;
    Object_171: Mesh;
    Object_173: Mesh;
    Object_176: Mesh;
    Object_180: Mesh;
    Object_183: Mesh;
    Object_186: Mesh;
    Object_189: Mesh;
    Object_192: Mesh;
    Object_195: Mesh;
    Object_198: Mesh;
    Object_201: Mesh;
    Object_204: Mesh;
    Object_207: Mesh;
    Object_210: Mesh;
    Object_213: Mesh;
    Object_216: Mesh;
    Object_219: Mesh;
    Object_222: Mesh;
    Object_225: Mesh;
    Object_228: Mesh;
    Object_231: Mesh;
    Object_234: Mesh;
    Object_237: Mesh;
    Object_240: Mesh;
    Object_243: Mesh;
    Object_246: Mesh;
    Object_249: Mesh;
    Object_252: Mesh;
    Object_255: Mesh;
    Object_258: Mesh;
    Object_261: Mesh;
    Object_264: Mesh;
    Object_267: Mesh;
    Object_270: Mesh;
    Object_273: Mesh;
    Object_276: Mesh;
    Object_279: Mesh;
    Object_282: Mesh;
    Object_285: Mesh;
    Object_288: Mesh;
    Object_291: Mesh;
    Object_294: Mesh;
    Object_297: Mesh;
    Object_300: Mesh;
    Object_303: Mesh;
    Object_306: Mesh;
    Object_309: Mesh;
    Object_312: Mesh;
    Object_315: Mesh;
    Object_318: Mesh;
    Object_320: Mesh;
    Object_323: Mesh;
    Object_326: Mesh;
    Object_329: Mesh;
    Object_332: Mesh;
    Object_335: Mesh;
    Object_338: Mesh;
    Object_341: Mesh;
  };
  materials: {
    [key: string]: MeshStandardMaterial;
    '11_-_Default': MeshStandardMaterial;
    material_0: MeshStandardMaterial;
    '22_-_Default': MeshStandardMaterial;
    material: MeshStandardMaterial;
    '19_-_Glass_Thin': MeshStandardMaterial;
    '04_-_Default': MeshStandardMaterial;
    Metal: MeshStandardMaterial;
    '06_-_Default': MeshStandardMaterial;
    '12_-_Car_Paint': MeshStandardMaterial;
    Material_27: MeshStandardMaterial;
    Ceramic: MeshStandardMaterial;
    '13_-_Brushed_Met': MeshStandardMaterial;
    '16_-_Matte_Plast': MeshStandardMaterial;
    '18_-_Rubber': MeshStandardMaterial;
    Material_26: MeshStandardMaterial;
    '01_-_Default': MeshStandardMaterial;
    '02_-_Default': MeshStandardMaterial;
    '23_-_Default': MeshStandardMaterial;
    '05_-_Default': MeshStandardMaterial;
    Solid_Glass: MeshStandardMaterial;
    '03_-_Default': MeshStandardMaterial;
    '24_-_Default': MeshStandardMaterial;
    '20_-_Polished_Al': MeshStandardMaterial;
    '17_-_Old_Copper': MeshStandardMaterial;
    Wall_Paint: MeshStandardMaterial;
  };
};

type Props = React.ComponentProps<'group'>

export function GirlRoom(props: Props) {
  const { nodes, materials } = useGLTF('/assets/Models/lo-fi_study_girlroom.glb') as unknown as GLTFResult
  const { positionX, positionY, positionZ, rotationX, rotationY, rotationZ, scale } = useControls({
    positionX: { value: 0, min: -20, max: 20, step: 0.1 },
    positionY: { value: 0, min: -100, max: 20, step: 0.1 },
    positionZ: { value: 0, min: -20, max: 100, step: 0.1 },
    rotationX: { value: -Math.PI / 2, min: -Math.PI, max: Math.PI, step: 0.1 },
    rotationY: { value: 0, min: -Math.PI, max: Math.PI, step: 0.1 },
    rotationZ: { value: 0, min: -Math.PI, max: Math.PI, step: 0.1 },
    scale: { value: 1, min: 0.1, max: 5, step: 0.1 }
  })

  return (
    <group {...props} dispose={null}
       position={[positionX, positionY, positionZ]}
      rotation={[rotationX, rotationY, rotationZ]}
      scale={scale}
      >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[8.283, 7.772, 13.078]} rotation={[0, -Math.PI / 9, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['11_-_Default']} position={[-12.257, -7.772, -9.456]} rotation={[0, Math.PI / 9, 0]} />
        </group>
        <group position={[8.088, 7.788, 12.014]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} position={[8.088, -7.788, -12.014]} scale={[-1, 1, 1]} />
        </group>
        <group position={[8.129, 7.843, 10.988]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials['22_-_Default']} position={[-8.129, -7.843, -10.988]} />
        </group>
        <group position={[0.133, 9.566, 0]} scale={[0.901, 0.901, 1]}> {/*Background */}
          <mesh geometry={nodes.Object_13.geometry} material={materials.material} position={[-0.148, -10.616, 0]} scale={[1.11, 1.11, 1]} />
        </group>
        <group position={[-7.805, 3.731, 15.194]} rotation={[0, 0, -1.484]} scale={[1.057, 1.057, 0.706]}>
          <mesh geometry={nodes.Object_16.geometry} material={materials['19_-_Glass_Thin']} position={[4.16, 7.048, -21.516]} rotation={[0, 0, 1.484]} scale={[0.946, 0.946, 1.416]} />
        </group>
        <group position={[-8.173, 5.695, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_19.geometry} material={materials['04_-_Default']} position={[4.461, -7.589, 3.109]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 5.695, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_22.geometry} material={materials.Metal} position={[4.461, -7.589, 3.109]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 5.695, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_25.geometry} material={materials['19_-_Glass_Thin']} position={[4.461, -7.589, 3.109]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 3.009, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_28.geometry} material={materials.Metal} position={[4.461, -7.589, 1.643]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 3.009, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_31.geometry} material={materials.Metal} position={[4.461, -7.589, 1.643]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 3.009, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_34.geometry} material={materials['04_-_Default']} position={[4.461, -7.589, 1.643]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 3.009, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_37.geometry} material={materials['19_-_Glass_Thin']} position={[4.461, -7.589, 1.643]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-7.805, 3.731, 15.194]} rotation={[0, 0, -1.484]} scale={[1.057, 1.057, 0.706]}>
          <mesh geometry={nodes.Object_40.geometry} material={materials['06_-_Default']} position={[4.16, 7.048, -21.516]} rotation={[0, 0, 1.484]} scale={[0.946, 0.946, 1.416]} />
        </group>
        <group position={[-8.173, 5.695, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_43.geometry} material={materials['12_-_Car_Paint']} position={[4.461, -7.589, 3.109]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.173, 3.009, 13.903]} rotation={[Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_46.geometry} material={materials['11_-_Default']} position={[4.461, -7.589, 1.643]} rotation={[-Math.PI / 2, 0, 0]} scale={0.546} />
        </group>
        <group position={[-8.804, 4.516, 11.834]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_49.geometry} material={materials.Material_27} position={[-4.516, -8.804, -11.834]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
        <group position={[-8.965, 7.435, 12.712]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_52.geometry} material={materials.Ceramic} position={[-7.435, -12.712, 8.965]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        </group>
        <group position={[-6.51, 8.836, 11.834]}>
          <mesh geometry={nodes.Object_55.geometry} material={materials.Material_27} position={[6.51, -8.836, -11.834]} />
        </group>
        <group position={[5.593, 7.258, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_58.geometry} material={materials['19_-_Glass_Thin']} position={[4.849, -0.581, -6.024]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.593, 7.258, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_61.geometry} material={materials['13_-_Brushed_Met']} position={[4.849, -0.581, -6.024]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.873, 7.376, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_64.geometry} material={materials['19_-_Glass_Thin']} position={[4.927, -0.533, -6.294]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.873, 7.376, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_67.geometry} material={materials.Metal} position={[4.927, -0.533, -6.294]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.032, 7.258, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_70.geometry} material={materials['19_-_Glass_Thin']} position={[4.849, -0.678, -5.482]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.032, 7.258, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_73.geometry} material={materials['04_-_Default']} position={[4.849, -0.678, -5.482]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.312, 7.376, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_76.geometry} material={materials['19_-_Glass_Thin']} position={[4.927, -0.63, -5.752]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[5.312, 7.376, 2.399]} rotation={[0, 1.309, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_79.geometry} material={materials['06_-_Default']} position={[4.927, -0.63, -5.752]} rotation={[-1.211, 0.095, 1.417]} scale={[-0.981, 0.668, 0.695]} />
        </group>
        <group position={[4.674, 7.126, 2.41]} rotation={[0, 1.396, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_82.geometry} material={materials['19_-_Glass_Thin']} position={[4.761, -1.043, -5.021]} rotation={[-1.322, 0.066, 1.454]} scale={[-0.992, 0.668, 0.68]} />
        </group>
        <group position={[4.674, 7.126, 2.41]} rotation={[0, 1.396, Math.PI / 2]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_85.geometry} material={materials['06_-_Default']} position={[4.761, -1.043, -5.021]} rotation={[-1.322, 0.066, 1.454]} scale={[-0.992, 0.668, 0.68]} />
        </group>
        <group position={[7.862, 6.819, 3.657]} rotation={[0, 0, 1.484]} scale={[1.353, 1.353, 0.904]}>
          <mesh geometry={nodes.Object_88.geometry} material={materials['19_-_Glass_Thin']} position={[-5.527, 5.349, -4.046]} rotation={[0, 0, -1.484]} scale={[0.739, 0.739, 1.106]} />
        </group>
        <group position={[7.862, 6.819, 3.657]} rotation={[0, 0, 1.484]} scale={[1.353, 1.353, 0.904]}>
          <mesh geometry={nodes.Object_91.geometry} material={materials['12_-_Car_Paint']} position={[-5.527, 5.349, -4.046]} rotation={[0, 0, -1.484]} scale={[0.739, 0.739, 1.106]} />
        </group>
        <group position={[8.26, 7.119, 4.688]} rotation={[0, 0, 0.087]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_94.geometry} material={materials['19_-_Glass_Thin']} position={[-5.911, -4.257, -4.688]} rotation={[0, 0, -0.087]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.26, 7.119, 4.688]} rotation={[0, 0, 0.087]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_97.geometry} material={materials['06_-_Default']} position={[-5.911, -4.257, -4.688]} rotation={[0, 0, -0.087]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.359, 7.128, 4.948]} rotation={[0, 0, 0.087]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_100.geometry} material={materials['19_-_Glass_Thin']} position={[-5.978, -4.257, -4.948]} rotation={[0, 0, -0.087]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.359, 7.128, 4.948]} rotation={[0, 0, 0.087]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_103.geometry} material={materials.Metal} position={[-5.978, -4.257, -4.948]} rotation={[0, 0, -0.087]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.342, 7.127, 5.208]} rotation={[0, 0, 0.175]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_106.geometry} material={materials['19_-_Glass_Thin']} position={[-6.315, -3.721, -5.208]} rotation={[0, 0, -0.175]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.342, 7.127, 5.208]} rotation={[0, 0, 0.175]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_109.geometry} material={materials['11_-_Default']} position={[-6.315, -3.721, -5.208]} rotation={[0, 0, -0.175]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[8.305, 7.123, 5.47]} rotation={[0, 0, 0.087]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_112.geometry} material={materials['19_-_Glass_Thin']} position={[5.942, -4.257, -5.47]} rotation={[0, 0, 0.087]} scale={[-0.668, 0.668, 1]} />
        </group>
        <group position={[8.305, 7.123, 5.47]} rotation={[0, 0, 0.087]} scale={[-1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_115.geometry} material={materials['13_-_Brushed_Met']} position={[5.942, -4.257, -5.47]} rotation={[0, 0, 0.087]} scale={[-0.668, 0.668, 1]} />
        </group>
        <group position={[6.141, 7.123, 6.915]} rotation={[0, 0, 1.484]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_118.geometry} material={materials['19_-_Glass_Thin']} position={[-5.098, 3.672, -6.915]} rotation={[0, 0, -1.484]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[6.141, 7.123, 6.915]} rotation={[0, 0, 1.484]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_121.geometry} material={materials['11_-_Default']} position={[-5.098, 3.672, -6.915]} rotation={[0, 0, -1.484]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[6.049, 6.78, 8.735]} rotation={[1.482, 0.001, 0.024]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_124.geometry} material={materials['19_-_Glass_Thin']} position={[-4.194, -6.117, 5.967]} rotation={[-1.473, 0.023, -0.003]} scale={[0.668, 0.998, 0.671]} />
        </group>
        <group position={[6.049, 6.78, 8.735]} rotation={[1.482, 0.001, 0.024]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_127.geometry} material={materials['12_-_Car_Paint']} position={[-4.194, -6.117, 5.967]} rotation={[-1.473, 0.023, -0.003]} scale={[0.668, 0.998, 0.671]} />
        </group>
        <group position={[5.701, 7.31, 10.233]} rotation={[0, 0, -3.054]} scale={[1.057, 1.057, 0.706]}>
          <mesh geometry={nodes.Object_130.geometry} material={materials['06_-_Default']} position={[5.975, 6.418, -14.49]} rotation={[0, 0, 3.054]} scale={[0.946, 0.946, 1.416]} />
        </group>
        <group position={[-1.893, 10.27, 12.768]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_133.geometry} material={materials['16_-_Matte_Plast']} position={[1.893, -12.768, 10.27]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-3.902, 7.481, 7.232]} rotation={[0, 0, 1.484]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_136.geometry} material={materials.Metal} position={[-4.751, -3.032, -7.232]} rotation={[0, 0, -1.484]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[-3.902, 7.481, 7.232]} rotation={[0, 0, 1.484]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_139.geometry} material={materials['19_-_Glass_Thin']} position={[-4.751, -3.032, -7.232]} rotation={[0, 0, -1.484]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[-6.371, 7.772, 9.078]} rotation={[0, -Math.PI / 9, 0]}>
          <mesh geometry={nodes.Object_142.geometry} material={materials['11_-_Default']} position={[2.882, -7.772, -10.709]} rotation={[0, Math.PI / 9, 0]} />
        </group>
        <group position={[-6.567, 7.788, 8.014]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Object_145.geometry} material={materials.material_0} position={[-6.567, -7.788, -8.014]} scale={[-1, 1, 1]} />
        </group>
        <group position={[-6.525, 7.843, 6.988]}>
          <mesh geometry={nodes.Object_148.geometry} material={materials['22_-_Default']} position={[6.525, -7.843, -6.988]} />
        </group>
        <group position={[-6.704, 4.604, 9.623]}>
          <group position={[-1.233, 0.78, 0.491]} rotation={[0.412, 0.607, -2.225]} scale={0.896}>
            <mesh geometry={nodes.Object_152.geometry} material={materials['18_-_Rubber']} position={[0.776, 15.468, -1.464]} rotation={[0.719, 0, 2.094]} scale={1.116} />
          </group>
          <group position={[-1.233, 0.78, -2.709]} rotation={[0, 0, -2.094]} scale={0.896}>
            <mesh geometry={nodes.Object_155.geometry} material={materials['18_-_Rubber']} position={[0.776, 10.677, -7.716]} rotation={[0, 0, 2.094]} scale={1.116} />
          </group>
          <group position={[1.28, -0.671, -0.007]} rotation={[-0.17, -0.285, -2.119]} scale={0.896}>
            <mesh geometry={nodes.Object_158.geometry} material={materials['18_-_Rubber']} position={[0.776, 3.545, -12.567]} rotation={[-0.331, 0, 2.094]} scale={1.116} />
          </group>
        </group>
        <group position={[-6.118, 4.324, 12.121]}>
          <group position={[0.004, 0, -0.185]} rotation={[-0.17, -0.285, -2.119]} scale={0.896}>
            <mesh geometry={nodes.Object_162.geometry} material={materials['22_-_Default']} position={[0.768, 3.54, -15.304]} rotation={[-0.331, 0, 2.094]} scale={1.116} />
          </group>
          <group position={[-0.04, 0.025, -0.041]} rotation={[Math.PI / 2, -Math.PI / 6, -1.24]} scale={0.896}>
            <mesh geometry={nodes.Object_165.geometry} material={materials['22_-_Default']} position={[15.474, 3.54, 0.768]} rotation={[-Math.PI / 2, -1.24, Math.PI / 6]} scale={1.116} />
          </group>
        </group>
        <group position={[-5.821, 4.163, 10.952]} rotation={[-0.17, -0.285, -2.119]} scale={0.896}>
          <mesh geometry={nodes.Object_168.geometry} material={materials.Material_26} position={[0.776, 3.545, -14.144]} rotation={[-0.331, 0, 2.094]} scale={1.116} />
        </group>
        <group position={[-5.102, -3.532, 8.322]} rotation={[1.385, 0.344, 0.063]} scale={0.573}>
          <mesh geometry={nodes.Object_171.geometry} material={materials.Material_27} position={[10.473, -13.825, -5.226]} rotation={[-1.396, 0, -Math.PI / 9]} scale={1.745} />
        </group>
        <group position={[0, 1.994, 5.271]} scale={0.854}>
          <mesh geometry={nodes.Object_176.geometry} material={materials.Ceramic} position={[0, -2.336, -6.173]} scale={1.171} />
        </group>
        {/* <group position={[5.129, 8.369, 11.654]}>
          <group position={[-0.038, 0.024, -0.018]} rotation={[Math.PI / 2, 0, 0]} scale={1.116}>
            <mesh geometry={nodes.Object_180.geometry} material={materials['19_-_Glass_Thin']} position={[-4.562, -10.426, 7.52]} rotation={[-Math.PI / 2, 0, 0]} scale={0.896} />
          </group>
          <group position={[-0.723, 0.111, 0.56]} rotation={[Math.PI / 2, -1.571, 0]}>
            <mesh geometry={nodes.Object_183.geometry} material={materials['02_-_Default']} position={[8.48, -12.215, 4.406]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          </group>
          <group position={[-0.001, -0.08, -0.018]} rotation={[1.319, 0, 0]} scale={[0.365, 0.365, 1]}>
            <mesh geometry={nodes.Object_186.geometry} material={materials['23_-_Default']} position={[-14.055, -36.544, 5.135]} rotation={[-1.17, 0, 0]} scale={[2.741, 1.184, 2.667]} />
          </group>
        </group> */}
        <group position={[6.881, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_189.geometry} material={materials['04_-_Default']} position={[4.421, -1.503, 4.155]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[6.881, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_192.geometry} material={materials['11_-_Default']} position={[4.421, -1.503, 4.155]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[6.881, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_195.geometry} material={materials['19_-_Glass_Thin']} position={[4.421, -1.503, 4.155]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[8.172, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_198.geometry} material={materials.Metal} position={[4.421, -1.503, 4.935]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[8.172, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_201.geometry} material={materials['06_-_Default']} position={[4.421, -1.503, 4.935]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[8.172, 7.321, 2.488]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_204.geometry} material={materials['19_-_Glass_Thin']} position={[4.421, -1.503, 4.935]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[6.881, 7.321, 2.488]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_207.geometry} material={materials['12_-_Car_Paint']} position={[4.421, -1.503, 4.155]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[8.172, 7.321, 2.488]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.656}>
          <mesh geometry={nodes.Object_210.geometry} material={materials['06_-_Default']} position={[4.421, -1.503, 4.935]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.604} />
        </group>
        <group position={[5.056, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_213.geometry} material={materials.Metal} position={[4.191, -3.068, 2.76]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[5.056, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_216.geometry} material={materials['11_-_Default']} position={[4.191, -3.068, 2.76]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[5.056, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_219.geometry} material={materials['19_-_Glass_Thin']} position={[4.191, -3.068, 2.76]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[5.056, 7.678, 5.621]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_222.geometry} material={materials['12_-_Car_Paint']} position={[4.191, -3.068, 2.76]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[6.484, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_225.geometry} material={materials['04_-_Default']} position={[4.191, -3.068, 3.539]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[6.484, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_228.geometry} material={materials['04_-_Default']} position={[4.191, -3.068, 3.539]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[6.484, 7.678, 5.621]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_231.geometry} material={materials['19_-_Glass_Thin']} position={[4.191, -3.068, 3.539]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[6.484, 7.678, 5.621]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_234.geometry} material={materials['11_-_Default']} position={[4.191, -3.068, 3.539]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[7.665, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_237.geometry} material={materials['04_-_Default']} position={[4.191, -4.881, 4.184]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[7.665, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          {/* <mesh geometry={nodes.Object_240.geometry} material={materials.Metal} position={[4.191, -4.881, 4.184]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} /> */}
        </group>
        <group position={[5.701, 7.31, 10.233]} rotation={[0, 0, -3.054]} scale={[1.057, 1.057, 0.706]}>
          <mesh geometry={nodes.Object_243.geometry} material={materials['19_-_Glass_Thin']} position={[5.975, 6.418, -14.49]} rotation={[0, 0, 3.054]} scale={[0.946, 0.946, 1.416]} />
        </group>
        <group position={[7.665, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_246.geometry} material={materials['19_-_Glass_Thin']} position={[4.191, -4.881, 4.184]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[7.665, 7.678, 8.942]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_249.geometry} material={materials['12_-_Car_Paint']} position={[4.191, -4.881, 4.184]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[4.979, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_252.geometry} material={materials.Metal} position={[4.191, -4.881, 2.718]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[4.979, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_255.geometry} material={materials.Metal} position={[4.191, -4.881, 2.718]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[4.979, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_258.geometry} material={materials['04_-_Default']} position={[4.191, -4.881, 2.718]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[4.979, 7.678, 8.942]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_261.geometry} material={materials['19_-_Glass_Thin']} position={[4.191, -4.881, 2.718]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[4.979, 7.678, 8.942]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_264.geometry} material={materials['11_-_Default']} position={[4.191, -4.881, 2.718]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[-8.581, 8.166, 13.903]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_267.geometry} material={materials['04_-_Default']} position={[4.457, -7.589, -4.684]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[-8.581, 8.166, 13.903]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_270.geometry} material={materials['04_-_Default']} position={[4.457, -7.589, -4.684]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[-8.581, 8.166, 13.903]} rotation={[Math.PI / 2, -1.571, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_273.geometry} material={materials['19_-_Glass_Thin']} position={[4.457, -7.589, -4.684]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[-3.902, 7.481, 6.975]} rotation={[0, 0, -1.309]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_276.geometry} material={materials['19_-_Glass_Thin']} position={[5.501, 1.224, -6.975]} rotation={[0, 0, 1.309]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[-4.667, 3.119, 6.978]} rotation={[0, 0, -0.175]}> {/*Book */}
          <mesh geometry={nodes.Object_279.geometry} material={materials.Material_25} position={[5.137, -2.261, -6.978]} rotation={[0, 0, 0.175]} />
        </group>
        <group position={[-6.743, -1.324, 6.98]} rotation={[0.001, 0.003, 0.12]}> {/* Keyboard */}
          <mesh geometry={nodes.Object_282.geometry} material={materials.Solid_Glass} position={[6.876, 0.497, -6.958]} rotation={[-0.002, -0.003, -0.12]} />
        </group>
        <group position={[-6.743, -1.324, 6.98]} rotation={[0.001, 0.003, 0.12]}> {/* Laptop Screen */}
          <mesh geometry={nodes.Object_285.geometry} material={materials['03_-_Default']} position={[6.876, 0.497, -6.958]} rotation={[-0.002, -0.003, -0.12]} />
        </group>
        <group position={[-7.722, 6.794, 7.369]} rotation={[0.134, -0.112, 0.88]} scale={[0.247, 0.247, 0.321]}>
          <mesh geometry={nodes.Object_288.geometry} material={materials.material_0} position={[-4.948, -41.652, -22.444]} rotation={[0, 0.175, -0.873]} scale={[4.051, 4.051, 3.116]} />
        </group>
        <group position={[-4.017, 5.757, 7.072]} rotation={[Math.PI / 2, -1.309, Math.PI / 2]} scale={0.321}>
          <mesh geometry={nodes.Object_291.geometry} material={materials.material_0} position={[-22.038, -20.569, -7.448]} rotation={[-0.262, Math.PI / 2, 0]} scale={3.116} />
        </group>
        {/* Start */}
        {/* <group position={[-5.061, -4.222, 7.475]} rotation={[0.134, -0.112, 0.88]} scale={[0.247, 0.247, 0.321]}>
          <mesh geometry={nodes.Object_294.geometry} material={materials.Solid_Glass} position={[21.833, -4.712, -27.504]} rotation={[0, 0.175, -0.873]} scale={[4.051, 4.051, 3.116]} />
        </group>
        <group position={[-4.778, -3.881, 7.336]} rotation={[-0.187, 0.123, 0.084]} scale={0.321}>
          <mesh geometry={nodes.Object_297.geometry} material={materials.material_0} position={[18.553, 14.634, -18.227]} rotation={[0.178, -0.136, -0.06]} scale={3.116} />
        </group>
        <group position={[-5.134, -4.093, 7.336]} rotation={[0, -0.175, 0]} scale={0.321}>
          <mesh geometry={nodes.Object_300.geometry} material={materials.material_0} position={[11.787, 12.754, -25.292]} rotation={[0, 0.175, 0]} scale={3.116} />
        </group>
        <group position={[-4.948, -3.95, 6.974]} scale={0.425}>
          <mesh geometry={nodes.Object_303.geometry} material={materials['24_-_Default']} position={[11.65, 9.301, -16.419]} scale={2.354} />
        </group>
        <group position={[-5.102, -3.532, 8.322]} rotation={[1.385, 0.344, 0.063]} scale={0.573}>
          <mesh geometry={nodes.Object_306.geometry} material={materials['13_-_Brushed_Met']} position={[10.473, -13.825, -5.226]} rotation={[-1.396, 0, -Math.PI / 9]} scale={1.745} />
        </group> */}
        {/*ENd */}
        <group position={[-7.658, 7.02, 6.974]} scale={[0.398, 0.398, 0.425]}>
          <mesh geometry={nodes.Object_309.geometry} material={materials['22_-_Default']} position={[19.225, -17.625, -16.419]} scale={[2.511, 2.511, 2.354]} />
        </group>
        <group position={[-4.667, 3.119, 6.978]} rotation={[0, 0, -0.175]}>
          <mesh geometry={nodes.Object_312.geometry} material={materials['20_-_Polished_Al']} position={[5.137, -2.261, -6.978]} rotation={[0, 0, 0.175]} />
        </group>
        <group position={[-5.894, 8.997, 12.712]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_315.geometry} material={materials.Ceramic} position={[5.894, -12.712, 8.997]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-6.743, -1.324, 6.98]} rotation={[0.001, 0.003, 0.12]}> {/* Laptop Border */}
          <mesh geometry={nodes.Object_318.geometry} material={materials['02_-_Default']} position={[6.876, 0.497, -6.958]} rotation={[-0.002, -0.003, -0.12]} />
        </group>
        <group position={[-2.858, 10.359, 8.826]} rotation={[0, 0, -Math.PI]} scale={[-0.64, 0.64, 0.64]}>
          <mesh geometry={nodes.Object_323.geometry} material={materials['17_-_Old_Copper']} position={[4.463, 16.175, -13.782]} rotation={[0, 0, -Math.PI]} scale={[-1.561, 1.561, 1.561]} />
        </group>
        <group position={[-8.581, 8.166, 13.903]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_326.geometry} material={materials['06_-_Default']} position={[4.457, -7.589, -4.684]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.546} />
        </group>
        <group position={[-3.902, 7.481, 6.975]} rotation={[0, 0, -1.309]} scale={[1.497, 1.497, 1]}>
          <mesh geometry={nodes.Object_329.geometry} material={materials['11_-_Default']} position={[5.501, 1.224, -6.975]} rotation={[0, 0, 1.309]} scale={[0.668, 0.668, 1]} />
        </group>
        <group position={[0, 1.994, 5.271]} scale={0.854}>
          <mesh geometry={nodes.Object_332.geometry} material={materials.Wall_Paint} position={[0, -2.336, -6.173]} scale={1.171} />
        </group>
        <group position={[-6, 2.994, 0.972]}>
          <mesh geometry={nodes.Object_335.geometry} material={materials.Ceramic} position={[6, -2.994, -0.972]} />
        </group>
        <group position={[7, 7.5, 1]}>
          <mesh geometry={nodes.Object_338.geometry} material={materials.Ceramic} position={[-7, -7.5, -1]} />
        </group>
        <group position={[-2.199, 8.411, 12.723]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.588, 1.654, 1]}>
          <mesh geometry={nodes.Object_341.geometry} material={materials['05_-_Default']} position={[-1.385, -7.694, -8.411]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.63, 1, 0.605]} />
        </group>
        <mesh geometry={nodes.Object_173.geometry} material={materials['01_-_Default']} position={[-0.001, -0.001, -0.001]} />
        <mesh geometry={nodes.Object_320.geometry} material={materials.material_0} position={[-0.001, -0.001, -0.001]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Models/lo-fi_study_girlroom.glb')
